### ISSUE TITLE
Add option to connect to Carvera via TCP

### ISSUE THREAD

**Issue by zvea** [Doridian/carvera-pendant#122]
It would be very helpful to have the option to connect to the machine over TCP rather than serial.  In principle, is there anything preventing that (differences in protocols etc) or is it simply a matter of implementing a different proxy target?

**Comment by Doridian** [comment]
@zvea It should simply be a matter to connect to it. I just didn't implement it because I don't personally use it. But it shouldn't be difficult to add, the protocol is identical.
